### ISSUE TITLE
NPE on AppVisibilityDetector

### ISSUE THREAD

**Issue by catt-stefano** [nearit/Android-SDK#25]
Here's the stacktrace

> Fatal Exception: java.lang.RuntimeException: Unable to create application com.XXXXXX: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
>        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6320)
>        at android.app.ActivityThread.access$1800(ActivityThread.java:221)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
>        at android.os.Handler.dispatchMessage(Handler.java:102)
>        at android.os.Looper.loop(Looper.java:158)
>        at android.app.ActivityThread.main(ActivityThread.java:7225)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
> Caused by java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
>        at it.near.sdk.utils.AppVisibilityDetector.checkIsMainProcess(SourceFile:91)
>        at it.near.sdk.utils.AppVisibilityDetector.init(SourceFile:50)
>        at it.near.sdk.geopolis.beacons.AltBeaconMonitor.initAppLifecycleMonitor(SourceFile:150)
>        at it.near.sdk.geopolis.GeopolisManager.initLifecycle(SourceFile:273)
>        at it.near.sdk.NearItManager.initLifecycleMethods(SourceFile:205)
>        at it.near.sdk.NearItManager.init(SourceFile:107)
>        at com.XXXXXX.onCreate(SourceFile:25)
>        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
>        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6317)
>        at android.app.ActivityThread.access$1800(ActivityThread.java:221)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
>        at android.os.Handler.dispatchMessage(Handler.java:102)
>        at android.os.Looper.loop(Looper.java:158)
>        at android.app.ActivityThread.main(ActivityThread.java:7225)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by catt-stefano** [comment]
Fixed in 2.5.5
